name: Exemple Workflow

on:
  push:
    branches:
      - main
      - lumiere   # 🔥 Ajout de ta branche personnelle
  pull_request:
    branches:
      - main
      - lumiere


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout du code
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Installer les dépendances
      - name: Installer les dépendances
        run: npm install

      # 4️⃣ Lancer les tests (facultatif)
      - name: Lancer les tests
        run: npm test

      # 5️⃣ Analyser le code avec ESLint
      - name: Exécuter ESLint
        run: npx eslint . --ext .js,.ts
